### ISSUE TITLE
Train Data

### ISSUE THREAD

**Issue by yimejky** [deepmind/tcia-ct-scan-dataset#1]
Is there any way to get your training data? There are no publicly available dataset for head and neck organs at risk segmentation.

**Comment by dpcoolmufa** [comment]
Is there any way to get the training dataset?

**Comment by shijianjian** [comment]
@harryaskham Any updates?

**Comment by SimonBiggs** [comment]
> There are no publicly available dataset for head and neck organs at risk segmentation.

The following dataset is publicly available:

https://wiki.cancerimagingarchive.net/display/Public/HNSCC

I have been able to make a model that is competitive with commercial products based on that dataset.

**Comment by shijianjian** [comment]
> > There are no publicly available dataset for head and neck organs at risk segmentation.
> 
> The following dataset is publicly available:
> 
> https://wiki.cancerimagingarchive.net/display/Public/HNSCC
> 
> I have been able to make a model that is competitive with commercial products based on that dataset.

@SimonBiggs This dataset seems not having labels. Is there any public datasets that contains similar semantic labels as in this repo?

**Comment by SimonBiggs** [comment]
Hi @shijianjian,

It does have labels, RT DICOM Structure files. That is the domain relevant label format in radiotherapy.

**Comment by SimonBiggs** [comment]
Also, as an extra tip, going to https://www.cancerimagingarchive.net/collections/ then filtering the table by RTSTRUCT:

![image](https://user-images.githubusercontent.com/6559099/174519492-fd77b100-69b0-4a4d-8f91-214b66fa3d95.png)

Gives all the labelled datasets :slightly_smiling_face:

**Comment by DorisxinDU** [comment]
@SimonBiggs hello, i try to download the dataset from the website, but it needs access too (said TCIA restricted), please can you let me know if I did something wrong. thanks for your help.(https://wiki.cancerimagingarchive.net/display/Public/HNSCC) https://wiki.cancerimagingarchive.net/display/Public/HNSCC

**Comment by cian** [comment]
@DorisxinDU Since we originally did this work TCIA have changed the licensing terms for the underlying datasets that we used. For more details on the new license see: https://wiki.cancerimagingarchive.net/download/attachments/4556915/TCIA%20License%20for%20Limited%20Access%20Collections%20woNC%20%28Final20211202%29.pdf
